package com.bibireden.playerex.config

import com.bibireden.playerex.math.FormulaEngine

/** Loader-neutral values consumed by common code. Fzzy classes stay in loader source sets. */
data class PlayerExConfigSnapshot(
    val relicDimensionRulesEnabled: Boolean = true,
    val relicDimensionRules: Map<String, List<Int>> = mapOf("minecraft:overworld" to listOf(100, 100, 80, 50, 30, 15, 5, 1), "minecraft:the_nether" to listOf(100, 50, 70, 90, 80, 60, 30, 10), "minecraft:the_end" to listOf(100, 10, 30, 60, 90, 100, 80, 50)),
    val relicChestsHaveLoot: Boolean = true,
    val relicChestChance: Int = 15,
    val relicChestLesserOrbChance: Int = 5,
    val relicChestGreaterOrbChance: Int = 1,
    val relicChestTomeChance: Int = 5,
    val relicOnlyPlayerKills: Boolean = false,
    val relicDragonDropsStone: Boolean = true,
    val relicMobLootChance: Int = 5,
    val relicMobRelicWeight: Int = 50,
    val relicMobPotionWeight: Int = 30,
    val relicMobLesserOrbWeight: Int = 5,
    val relicMobGreaterOrbWeight: Int = 1,
    val relicMobTomeWeight: Int = 10,
    val relicMobBlacklist: List<String> = emptyList(),
    val disableUI: Boolean = false,
    val resetOnDeath: Boolean = false,
    val weaponLevelingEnabled: Boolean = true,
    val armorLevelingEnabled: Boolean = true,
    val weaponMaxLevel: Int = 500,
    val armorMaxLevel: Int = 500,
    val weaponDamagePerLevel: Double = 0.1,
    val armorPerLevel: Double = 0.1,
    val armorReductionPerLevel: Double = 0.1,
    val armorMaxReduction: Double = 25.0,
    val weaponXpFromPassive: Int = -1,
    val weaponXpFromHostile: Int = -1,
    val weaponXpFromBoss: Int = -1,
    val armorXpFromPassive: Int = -1,
    val armorXpFromHostile: Int = -1,
    val armorXpFromBoss: Int = -1,
    val itemXpFromPassive: Int = 10,
    val itemXpFromHostile: Int = 20,
    val itemXpFromBoss: Int = 100,
    val healthRegenerationLifecycle: HealthRegenerationLifecycle = HealthRegenerationLifecycle.ON_EVERY_SECOND,
    val messageOnItemBreak: Boolean = true,
    val destroyCurseOfBinding: Boolean = true,
    val itemBreakingEnabled: Boolean = true,
    val infiniteItemBreaking: Boolean = false,
    val timesItemCanBreak: Int = 3,
    val skillPointsPerLevelUp: Int = 1,
    val restorativeForceTicks: Int = 600,
    val restorativeForceMultiplier: Int = 110,
    val expNegationFactor: Int = 95,
    val levelFormula: String = FormulaEngine.DEFAULT_LEVEL_FORMULA,
    val weaponFormula: String = FormulaEngine.DEFAULT_ITEM_FORMULA,
    val armorFormula: String = FormulaEngine.DEFAULT_ITEM_FORMULA
) {
    fun normalized(): PlayerExConfigSnapshot = copy(
        relicDimensionRules = relicDimensionRules.filter { (id, values) -> net.minecraft.resources.ResourceLocation.tryParse(id) != null && values.size == 8 }.mapValues { (_, values) -> listOf(values[0].coerceIn(0, 200)) + values.drop(1).map { it.coerceIn(0, 100) } },
        relicChestChance = relicChestChance.coerceIn(0, 100),
        relicChestLesserOrbChance = relicChestLesserOrbChance.coerceIn(0, 100),
        relicChestGreaterOrbChance = relicChestGreaterOrbChance.coerceIn(0, 100),
        relicChestTomeChance = relicChestTomeChance.coerceIn(0, 100),
        relicMobLootChance = relicMobLootChance.coerceIn(0, 100),
        relicMobRelicWeight = relicMobRelicWeight.coerceIn(0, 100),
        relicMobPotionWeight = relicMobPotionWeight.coerceIn(0, 100),
        relicMobLesserOrbWeight = relicMobLesserOrbWeight.coerceIn(0, 100),
        relicMobGreaterOrbWeight = relicMobGreaterOrbWeight.coerceIn(0, 100),
        relicMobTomeWeight = relicMobTomeWeight.coerceIn(0, 100),
        weaponMaxLevel = weaponMaxLevel.coerceIn(0, 10000),
        armorMaxLevel = armorMaxLevel.coerceIn(0, 10000),
        weaponDamagePerLevel = weaponDamagePerLevel.takeIf { it.isFinite() }?.coerceIn(0.0, 1000.0) ?: 0.1,
        armorPerLevel = armorPerLevel.takeIf { it.isFinite() }?.coerceIn(0.0, 1000.0) ?: 0.1,
        armorReductionPerLevel = armorReductionPerLevel.takeIf { it.isFinite() }?.coerceIn(0.0, 25.0) ?: 0.1,
        armorMaxReduction = armorMaxReduction.takeIf { it.isFinite() }?.coerceIn(0.0, 25.0) ?: 25.0,
        weaponXpFromPassive = weaponXpFromPassive.coerceAtLeast(-1),
        weaponXpFromHostile = weaponXpFromHostile.coerceAtLeast(-1),
        weaponXpFromBoss = weaponXpFromBoss.coerceAtLeast(-1),
        armorXpFromPassive = armorXpFromPassive.coerceAtLeast(-1),
        armorXpFromHostile = armorXpFromHostile.coerceAtLeast(-1),
        armorXpFromBoss = armorXpFromBoss.coerceAtLeast(-1),
        itemXpFromPassive = itemXpFromPassive.coerceAtLeast(0),
        itemXpFromHostile = itemXpFromHostile.coerceAtLeast(0),
        itemXpFromBoss = itemXpFromBoss.coerceAtLeast(0),
        timesItemCanBreak = timesItemCanBreak.coerceIn(0, 10000),
        skillPointsPerLevelUp = skillPointsPerLevelUp.coerceAtLeast(0),
        restorativeForceTicks = restorativeForceTicks.coerceAtLeast(1),
        restorativeForceMultiplier = restorativeForceMultiplier.coerceAtLeast(100),
        expNegationFactor = expNegationFactor.coerceIn(0, 100)
    )
}
